'use strict';
// Prepares everything the application uses offline. Runs in postinstall.
//
//  1. KaTeX  -> src/vendor/katex/   (formulas)
//  2. Lucide -> src/icons.js        (SVG icons, generated from the package)
//  3. JetBrains Mono -> src/fonts/  (the UI and code font)
//
// The icons used to be Font Awesome glyphs (&#xf07b; and the like) taken from
// JetBrainsMono Nerd Font: the glyphs only drew if the Nerd font loaded, and
// the font itself weighed 4 x ~1 MB. Now they are ordinary Lucide SVGs and the
// font is regular JetBrains Mono (the same glyphs plus Cyrillic, a quarter of
// the weight in total).
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const NM = path.join(ROOT, 'node_modules');

function copyDir(from, to) {
  fs.mkdirSync(to, { recursive: true });
  for (const entry of fs.readdirSync(from, { withFileTypes: true })) {
    const s = path.join(from, entry.name);
    const d = path.join(to, entry.name);
    if (entry.isDirectory()) copyDir(s, d);
    else fs.copyFileSync(s, d);
  }
}

function rel(p) { return path.relative(process.cwd(), p); }

// ───────────────────────────────────────────────────────────── 1. KaTeX

(function vendorKatex() {
  const SRC = path.join(NM, 'katex', 'dist');
  const DST = path.join(ROOT, 'src', 'vendor', 'katex');
  if (!fs.existsSync(SRC)) {
    console.error('[vendor] KaTeX not found in', SRC, '— run npm install');
    return;
  }
  fs.rmSync(DST, { recursive: true, force: true });
  copyDir(SRC, DST);
  // contrib/auto-render is not needed: we cut the formulas out into
  // placeholders ourselves and render them by hand (more reliable than a
  // post-hoc autorender pass).
  fs.rmSync(path.join(DST, 'contrib'), { recursive: true, force: true });
  const ver = require(path.join(SRC, '..', 'package.json')).version;
  console.log('[vendor] KaTeX ' + ver + ' ->', rel(DST));
})();

// ───────────────────────────────────────────────────────────── 2. Lucide

// The icons the interface actually uses. Lucide ships ~1600 files; the build
// takes only these and inlines them into one small module.
const USED_ICONS = [
  'file-text', 'folder-open', 'folder', 'file', 'arrow-left', 'arrow-right',
  'arrow-up', 'pencil', 'save', 'zoom-in', 'zoom-out', 'folder-output',
  'x', 'copy', 'eye-off', 'printer', 'folder-search',
  'search', 'file-down', 'file-code', 'check', 'list-tree', 'menu', 'plus', 'chevron-left', 'chevron-right',
  // note ring: clipboard
  'scissors', 'clipboard-paste',
  // "Path" in the ring: a signpost, not a folder — it means the path to a
  // file, not a directory.
  'signpost',
  // Task-list checkboxes (- [x] / 1. [ ]): marked renders them as native
  // <input type=checkbox>, which looked out of place in the dark theme.
  'square-check-big', 'square',
];

(function vendorLucide() {
  const SRC = path.join(NM, 'lucide-static', 'icons');
  const DST = path.join(ROOT, 'src', 'icons.js');
  if (!fs.existsSync(SRC)) {
    console.error('[vendor] lucide-static not found in', SRC, '— run npm install');
    return;
  }

  const bodies = {};
  const missing = [];
  for (const name of USED_ICONS) {
    const p = path.join(SRC, name + '.svg');
    if (!fs.existsSync(p)) { missing.push(name); continue; }
    let svg = fs.readFileSync(p, 'utf8');
    svg = svg.replace(/<!--[\s\S]*?-->/g, '').trim();
    const m = svg.match(/^<svg[^>]*?>([\s\S]*)<\/svg>$/);
    if (!m) { missing.push(name + ' (unrecognised)'); continue; }
    bodies[name] = m[1].trim().replace(/\s+/g, ' ');
  }
  if (missing.length) {
    console.error('[vendor] lucide: icons not found:', missing.join(', '));
    process.exitCode = 1;
    return;
  }

  const ver = require(path.join(NM, 'lucide-static', 'package.json')).version;
  const entries = Object.keys(bodies).sort()
    .map((n) => '    ' + JSON.stringify(n) + ': ' + JSON.stringify(bodies[n]) + ',')
    .join('\n');

  const out = `'use strict';
/*
 * Lucide SVG icons. This file is GENERATED by scripts/vendor.js from the
 * lucide-static package — edit USED_ICONS in vendor.js, not this file.
 *
 * Inlined rather than <use href="sprite.svg#...">: index.html carries a strict
 * CSP (default-src 'none'), and an external reference in <use> is a fetch,
 * which it does not allow. Inlining works offline and without a network for
 * certain.
 *
 * The icons used to be Font Awesome glyphs (&#xf07b;) from Nerd Font — they
 * needed an icon font and silently vanished if the font failed to load.
 *
 * lucide-static ${ver} (ISC).
 */
(function (global) {
  const ICONS = {
${entries}
  };

  const ATTRS = 'viewBox="0 0 24 24" fill="none" stroke="currentColor"'
    + ' stroke-width="2" stroke-linecap="round" stroke-linejoin="round"';

  /** SVG markup for an icon. class is added to .ico-svg. */
  function icon(name, cls) {
    const body = ICONS[name];
    if (!body) return '';
    return '<svg class="ico-svg' + (cls ? ' ' + cls : '') + '" ' + ATTRS
      + ' aria-hidden="true" focusable="false">' + body + '</svg>';
  }

  /** Fills every <span data-i="name"> inside root (the whole document by default). */
  function hydrate(root) {
    const scope = root || document;
    scope.querySelectorAll('[data-i]').forEach((el) => {
      el.innerHTML = icon(el.getAttribute('data-i'), el.getAttribute('data-i-cls') || '');
    });
  }

  global.MDV_ICONS = { ICONS, icon, hydrate };
})(typeof window !== 'undefined' ? window : globalThis);

if (typeof module !== 'undefined' && module.exports) module.exports = globalThis.MDV_ICONS;
`;

  fs.writeFileSync(DST, out, 'utf8');
  console.log('[vendor] Lucide ' + ver + ' -> ' + rel(DST) + ' (' + Object.keys(bodies).length + ' icons)');
})();

// ─────────────────────────────────────────────────── 3. JetBrains Mono

// Only the subsets and weights that are needed: Cyrillic (the interface is
// Russian) and Latin (code, identifiers). Weights: 400/500/700 upright and 400
// italic. The Nerd Font (4 x ~1 MB) is no longer needed.
const FONT_SUBSETS = ['cyrillic', 'latin'];
const FONT_FACES = [
  { weight: 400, style: 'normal', file: 'jetbrains-mono-{s}-400-normal.woff2' },
  { weight: 500, style: 'normal', file: 'jetbrains-mono-{s}-500-normal.woff2' },
  { weight: 700, style: 'normal', file: 'jetbrains-mono-{s}-700-normal.woff2' },
  { weight: 400, style: 'italic', file: 'jetbrains-mono-{s}-400-italic.woff2' },
];

// Unicode ranges for @font-face. Without them the browser loads the cyrillic
// file even for Latin letters, and the latin file for Cyrillic.
const SUBSET_RANGES = {
  cyrillic: 'U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116',
  latin: 'U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA,'
    + ' U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191,'
    + ' U+2193, U+2212, U+2215, U+FEFF, U+FFFD',
};

(function vendorFont() {
  const SRC = path.join(NM, '@fontsource', 'jetbrains-mono', 'files');
  const DST = path.join(ROOT, 'src', 'fonts');
  if (!fs.existsSync(SRC)) {
    console.error('[vendor] @fontsource/jetbrains-mono not found in', SRC, '— run npm install');
    return;
  }
  fs.mkdirSync(DST, { recursive: true });

  let total = 0;
  for (const face of FONT_FACES) {
    for (const subset of FONT_SUBSETS) {
      const name = face.file.replace('{s}', subset);
      const from = path.join(SRC, name);
      if (!fs.existsSync(from)) { console.error('[vendor] no font file', name); continue; }
      const to = path.join(DST, name);
      fs.copyFileSync(from, to);
      total += fs.statSync(to).size;
    }
  }

  // The Nerd Font is no longer used: the icons are SVG now.
  for (const f of fs.readdirSync(DST)) {
    if (/NerdFont/i.test(f)) {
      fs.unlinkSync(path.join(DST, f));
      console.log('[vendor] removed obsolete file', f);
    }
  }

  // Generate the @font-face blocks, so that the CSS cannot drift away from
  // the files actually copied.
  const blocks = [];
  for (const face of FONT_FACES) {
    for (const subset of FONT_SUBSETS) {
      const file = face.file.replace('{s}', subset);
      if (!fs.existsSync(path.join(DST, file))) continue;
      blocks.push(
        '@font-face {\n'
        + '    font-family: "JetBrainsMono";\n'
        + `    src: url("fonts/${file}") format("woff2");\n`
        + `    font-weight: ${face.weight};\n`
        + `    font-style: ${face.style};\n`
        + `    font-display: swap;\n`
        + `    unicode-range: ${SUBSET_RANGES[subset]};\n`
        + '}'
      );
    }
  }
  fs.writeFileSync(path.join(ROOT, 'src', 'fonts.css'), blocks.join('\n') + '\n', 'utf8');

  console.log('[vendor] JetBrains Mono -> ' + rel(DST)
    + ' (' + (total / 1024).toFixed(0) + ' KB woff2, ' + blocks.length + ' @font-face)');
})();
